// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/HOangAG2207/GoBeK03/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// Health is an autogenerated mock type for the Health type
type Health struct {
	mock.Mock
}

// CheckHealth provides a mock function with no fields
func (_m *Health) CheckHealth() (*model.Health, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CheckHealth")
	}

	var r0 *model.Health
	var r1 error
	if rf, ok := ret.Get(0).(func() (*model.Health, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *model.Health); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Health)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealth creates a new instance of Health. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealth(t interface {
	mock.TestingT
	Cleanup(func())
}) *Health {
	mock := &Health{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
